import { Metadata } from 'next'
import UrlInput from '@/components/urlInput'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main className='pt-16 flex flex-col space-y-6 items-center justify-center max-w-7xl'>
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput /><UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      <UrlInput />
      
    </main>
  )
}